export const links = [
  {
    name: "Home",
    hash: "#hero",
  },
  {
    name: "About",
    hash: "#about",
  },
  {
    name: "Projects",
    hash: "#projects",
  },
  {
    name: "Skills",
    hash: "#skills",
  },
  {
    name: "Experience",
    hash: "#experience",
  },
] as const;

export const skillsData = [
  "TypeScript",
  "React",
  "Next.js",
  "Node.js",
  "Bun",
  "Tailwind",
  "MongoDB",
  "PostgreSQL",
  "AWS",
  "GraphQL",
  "Apollo",
  "Kafka",
  "RabbitMQ",

export const projectsData = [
  {
    title: "Arbo",
    description: "I worked as a full-stack developer on this startup.",
    tags: [
      "Typescript",
      "React",
      "Next.js",
      "Node.js",
      "Fastify",
      "Express",
      "Loopback.io 2",
      "MongoDB",
      "PostgreSQL",
      "Bootstrap",
      "Prisma",
      "Serverless Framework",
      "AWS",
      "Lambda",
    ],
    imageUrl: arbo,
  },
  {
    title: "Resolv Tech",
    description: "I worked as a full-stack developer on this startup.",
    tags: [
      "Typescript",
      "React",
      "Vite",
      "Material-UI",
      "Node.js",
      "PostgreSQL",
      "MongoDB",
      "MariaDB",
      "Serverless Framework",
      "AWS",
      "RDS",
      "Bastion",
      "Lambda",
      "Clean Architecture",
    ],
    imageUrl: resolv,
  },
  {
    title: "Afinz",
    description: "I worked as a backend developer on this fintech.",
    tags: [
      "Typescript",
      "Node.js",
      "PostgreSQL",
      "Serverless Framework",
      "Keycloak",
      "AWS",
      "RDS",
      "Lambda",
      "Clean Architecture",
    ],
    imageUrl: afinz,
  },
  {
    title: "Soipo",
    description: "I worked as a full-stack developer on this consultancy.",
    tags: [
      "Typescript",
      "Node.js",
      "PostgreSQL",
      "Serverless Framework",
      "AWS",
      "RDS",
      "Cognito",
      "API Gateway",
      "Socket.io",
      "Pusher",
      "Shopify",
      "BigCommerce",
    ],
    imageUrl: soipo,
  },
  {
    title: "Geritch Restaurant",
    description: "A case study of CSS BEM model",
    tags: ["React", "HTML", "CSS"],
    imageUrl: soipo,
  },
] as const;
